name: awesome_video_downloader
description: A Flutter plugin for downloading videos in various formats (HLS, DASH, MP4) with support for background downloads, progress tracking, and offline playback.
version: 0.1.0+1
homepage: https://github.com/AkmaljonAbdirakhimov/awesome_video_downloader
repository: https://github.com/AkmaljonAbdirakhimov/awesome_video_downloader
issue_tracker: https://github.com/AkmaljonAbdirakhimov/awesome_video_downloader/issues
documentation: https://github.com/AkmaljonAbdirakhimov/awesome_video_downloader/blob/main/README.md

environment:
  sdk: ^3.5.3
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  integration_test:
    sdk: flutter

topics:
  - video
  - download
  - hls
  - dash
  - streaming

flutter:
  plugin:
    platforms:
      android:
        package: uz.fluttterwithakmaljon.awesome_video_downloader
        pluginClass: AwesomeVideoDownloaderPlugin
      ios:
        pluginClass: AwesomeVideoDownloaderPlugin
        minimumOSVersion: 11.0